package bindings.adw

import kotlinx.cinterop.CPointer
import native.adwaita.*

fun CPointer<AdwActionRow>.asActionRow(): ActionRow = ActionRow(this)
fun CPointer<AdwApplication>.asApplication(): Application = Application(this)
fun CPointer<AdwAboutWindow>.asAboutWindow(): AboutWindow = AboutWindow(this)
fun CPointer<AdwApplicationWindow>.asApplicationWindow(): ApplicationWindow = ApplicationWindow(this)
fun CPointer<AdwAvatar>.asAvatar(): Avatar = Avatar(this)
fun CPointer<AdwButtonContent>.asButtonContent(): ButtonContent = ButtonContent(this)
fun CPointer<AdwClamp>.asClamp(): Clamp = Clamp(this)
fun CPointer<AdwEntryRow>.asEntryRow(): EntryRow = EntryRow(this)
fun CPointer<AdwHeaderBar>.asHeaderBar(): HeaderBar = HeaderBar(this)
fun CPointer<AdwMessageDialog>.asMessageDialog(): MessageDialog = MessageDialog(this)
fun CPointer<AdwPasswordEntryRow>.asPasswordEntryRow(): PasswordEntryRow = PasswordEntryRow(this)
fun CPointer<AdwPreferencesGroup>.asPreferencesGroup(): PreferencesGroup = PreferencesGroup(this)
fun CPointer<AdwPreferencesPage>.asPreferencesPage(): PreferencesPage = PreferencesPage(this)
fun CPointer<AdwPreferencesRow>.asPreferencesRow(): PreferencesRow = PreferencesRow(this)
fun CPointer<AdwPreferencesWindow>.asPreferencesWindow(): PreferencesWindow = PreferencesWindow(this)
fun CPointer<AdwStatusPage>.asStatusPage(): StatusPage = StatusPage(this)
fun CPointer<AdwTabBar>.asTabBar(): TabBar = TabBar(this)
fun CPointer<AdwTabView>.asTabView(): TabView = TabView(this)
fun CPointer<AdwTabPage>.asTabPage(): TabPage = TabPage(this)
fun CPointer<AdwToast>.asToast(): Toast = Toast(this)
fun CPointer<AdwToastOverlay>.asToastOverlay(): ToastOverlay = ToastOverlay(this)
fun CPointer<AdwViewStack>.asViewStack(): ViewStack = ViewStack(this)
fun CPointer<AdwViewStackPage>.asViewStackPage(): ViewStackPage = ViewStackPage(this)
fun CPointer<AdwViewSwitcher>.asViewSwitcher(): ViewSwitcher = ViewSwitcher(this)
fun CPointer<AdwViewSwitcherBar>.asViewSwitcherBar(): ViewSwitcherBar = ViewSwitcherBar(this)
fun CPointer<AdwViewSwitcherTitle>.asViewSwitcherTitle(): ViewSwitcherTitle = ViewSwitcherTitle(this)
fun CPointer<AdwWindow>.asWindow(): Window = Window(this)
