package bindings.gtk

import bindings.gtk.internal.*
import kotlinx.cinterop.CPointer
import native.gtk.*

fun CPointer<GtkAboutDialog>.asAboutDialog(): AboutDialog = AboutDialog(this)
fun CPointer<GtkAdjustment>.asAdjustment(): Adjustment = Adjustment(this)
fun CPointer<GtkActionable>.asActionable(): Actionable = ActionableWrapper(this)
fun CPointer<GtkApplication>.asApplication(): Application = Application(this)
fun CPointer<GtkApplicationWindow>.asApplicationWindow(): ApplicationWindow = ApplicationWindow(this)
fun CPointer<GtkAspectFrame>.asAspectFrame(): AspectFrame = AspectFrame(this)
fun CPointer<GtkBox>.asBox(): Box = Box(this)
fun CPointer<GtkCenterBox>.asCenterBox(): CenterBox = CenterBox(this)
fun CPointer<GtkCheckButton>.asCheckButton(): CheckButton = CheckButton(this)
fun CPointer<GtkButton>.asButton(): Button = Button(this)
fun CPointer<GtkDialog>.asDialog(): Dialog = Dialog(this)
fun CPointer<GtkEditable>.asEditable(): Editable = EditableWrapper(this)
fun CPointer<GtkGrid>.asGrid(): Grid = Grid(this)
fun CPointer<GtkGridView>.asGridView(): GridView = GridView(this)
fun CPointer<GtkHeaderBar>.asHeaderBar(): HeaderBar = HeaderBar(this)
fun CPointer<GtkImage>.asImage(): Image = Image(this)
fun CPointer<GtkLabel>.asLabel(): Label = Label(this)
fun CPointer<GtkLevelBar>.asLevelBar(): LevelBar = LevelBar(this)
fun CPointer<GtkLinkButton>.asLinkButton(): LinkButton = LinkButton(this)
fun CPointer<GtkListBox>.asListBox(): ListBox = ListBox(this)
fun CPointer<GtkListBoxRow>.asListBoxRow(): ListBoxRow = ListBoxRow(this)
fun CPointer<GtkListItem>.asListItem(): ListItem = ListItem(this)
fun CPointer<GtkListView>.asListView(): ListView = ListView(this)
fun CPointer<GtkListItemFactory>.asListItemFactory(): ListItemFactory = ListItemFactory(this)
fun CPointer<GtkSignalListItemFactory>.asListItemFactory(): ListItemFactory = ListItemFactory(this)
fun CPointer<GtkLockButton>.asLockButton(): LockButton = LockButton(this)
fun CPointer<GtkMenuButton>.asMenuButton(): MenuButton = MenuButton(this)
fun CPointer<GtkMessageDialog>.asMessageDialog(): MessageDialog = MessageDialog(this)
fun CPointer<GtkNative>.asNative(): Native = NativeWrapper(this)
fun CPointer<GtkOrientable>.asOrientable(): Orientable = OrientableWrapper(this)
fun CPointer<GtkPopover>.asPopover(): Popover = Popover(this)
fun CPointer<GtkRoot>.asRoot(): Root = RootWrapper(this)
fun CPointer<GtkScrollable>.asScrollable(): Scrollable = ScrollableWrapper(this)
fun CPointer<GtkScrolledWindow>.asScrolledWindow(): ScrolledWindow = ScrolledWindow(this)
fun CPointer<GtkSelectionModel>.asSelectionModel(): SelectionModel = SelectionModelWrapper(this)
fun CPointer<GtkSeparator>.asSeparator(): Separator = Separator(this)
fun CPointer<GtkShortcutManager>.asShortcutsManager(): ShortcutManager = ShortcutManagerWrapper(this)
fun CPointer<GtkShortcutsWindow>.asShortcutsWindow(): ShortcutsWindow = ShortcutsWindow(this)
fun CPointer<GtkSearchBar>.asSearchBar(): SearchBar = SearchBar(this)
fun CPointer<GtkSingleSelection>.asSingleSelection(): SingleSelection = SingleSelection(this)
fun CPointer<GtkStack>.asStack(): Stack = Stack(this)
fun CPointer<GtkStackPage>.asStackPage(): StackPage = StackPage(this)
fun CPointer<GtkStackSidebar>.asStackSidebar(): StackSidebar = StackSidebar(this)
fun CPointer<GtkStringList>.asStringList(): StringList = StringList(this)
fun CPointer<GtkStringObject>.asStringObject(): StringObject = StringObject(this)
fun CPointer<GtkSwitch>.asSwitch(): Switch = Switch(this)
fun CPointer<GtkToggleButton>.asToggleButton(): ToggleButton = ToggleButton(this)
fun CPointer<GtkTreeListModel>.asTreeListModel(): TreeListModel = TreeListModel(this)
fun CPointer<GtkTreeListRow>.asTreeListRow(): TreeListRow = TreeListRow(this)
fun CPointer<GtkTreeExpander>.asTreeExpander(): TreeExpander = TreeExpander(this)
fun CPointer<GtkWidget>.asWidget(): Widget = Widget(this)
fun CPointer<GtkWindow>.asWindow(): Window = Window(this)